### ISSUE TITLE
En tant que mainteneur du projet, je veux une action GitHub qui exécute semantic-release afin de déclencher les releases automatiquement lors des merges sur main et support/***.

### ISSUE THREAD

**Issue by bdelion** [bdelion/weather-harvest#46]
📌 Description
En tant que mainteneur du projet, je veux une action GitHub qui exécute semantic-release afin de déclencher les releases automatiquement lors des merges sur main et support/***.

💡 Solution proposée

- Créer un fichier de workflow GitHub Actions.
- Configurer les permissions pour permettre la création de releases et le push des tags.
- Vérifier le bon déclenchement de l’action.

✅ Checklist

- [ ] Créer un fichier .github/workflows/release.yml.
- [ ] Configurer le workflow pour exécuter semantic-release.
- [ ] Vérifier que la release est bien déclenchée après un merge.

📝 Exemple

```yaml
name: Release

on:
  push:
    branches:
      - main
      - support/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
